[package]
name = "dirpin-client"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
dirpin-common = { path = "../dirpin-common" }
tokio = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
eyre = { workspace = true }
shellexpand = "3.1.0"

