## where to store your database, default is your system data directory
## linux/mac: ~/.local/share/dirpin/pins.db
## windows: %USERPROFILE%/.local/share/dirpin/pins.db
# db_path = "~/.pins.db"

## where to store your encryption key, default is your system data directory
## linux/mac: ~/.local/share/dirpin/key
## windows: %USERPROFILE%/.local/share/dirpin/key
# key_path = "~/.key"

## where to store your auth session token, default is your system data directory
## linux/mac: ~/.local/share/dirpin/session
## windows: %USERPROFILE%/.local/share/dirpin/session
# session_path = "~/.session"


## The remote server address for syncing and backup
# server_address = "https://address.com"

## enable or disable automatic sync
# auto_sync = true

## how often to sync history. note that this is only triggered when a command
## is ran, so sync intervals may well be longer
## set it to 0 to sync after every command
# sync_frequency = "10m"
