[package]
name = "dirpin-common"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }
base64 = { workspace = true }
getrandom = "0.2.15"
